### ISSUE TITLE
Punch a hole in azcam firewall for bigpop

### ISSUE THREAD

**Issue by srswinde** [bjweiner/ARTN#15]

**Comment by srswinde** [comment]
I will do this tomorrow.

**Comment by dsand** [comment]
Hey Scott -- Any luck with this?

**Comment by srswinde** [comment]
I believe so. I added the AzCam ports to the firewall rules and turned the firewall back on. I didn't have any with the camera driver. I say we close this issue if the next ARTN run doesn't have any problems.

**Comment by dsand** [comment]
Scott and I checked this tonight.  The firewall seems to be happy with the camera driver now.
