### ISSUE TITLE
Camera and telescope drivers dropping out

### ISSUE THREAD

**Issue by bjweiner** [bjweiner/ARTN#3]
Need to figure out why the AzCam and BIG61 drivers sometimes lose communication, and 1) have a way of detecting when this happens / issuing a warning; 2) friendly way of restarting driver ideally without stopping RTS2 and the queue; 3) fix it so it doesn't happen.

**Comment by srswinde** [comment]
Lets keep an  eye out for this and comment here every time it happens.

**Comment by dsand** [comment]
Petr just talked about resolving this issue, he thinks he knows what is wrong.  Scott and Petr should mind-meld.

**Comment by srswinde** [comment]
I think this problem has been solved or has morphed into new more specific problems. I am closing this one.
