### ISSUE TITLE
rsync to scopenet

### ISSUE THREAD

**Issue by srswinde** [bjweiner/ARTN#41]
I believe I have a cronjob that will rsync the data to the proper place on scopent. @pndaly could you make sure this is correct.

**Comment by pndaly** [comment]
Looks OK .... will re-process 20190916, 20190917, 20190918 and 20190930 later which should send
emails to people who have data. Will report back some more then.

**Comment by pndaly** [comment]
Looks like this works for on-sky data. I'm not sure skyflats were completed (at the telescope) though.

**Comment by dsand** [comment]
I think rsync is working--I am closing this one.
